name: ShadowVPN Multiplatform Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build for ${{ matrix.runtime }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [ "win-x64", "linux-x64" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish
        run: |
          dotnet publish ShadowVPN.Desktop/ShadowVPN.Desktop.csproj \
            -r ${{ matrix.runtime }} \
            -p:PublishSingleFile=true \
            --self-contained true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -o publish/${{ matrix.runtime }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ShadowVPN_${{ matrix.runtime }}
          path: |
            publish/${{ matrix.runtime }}/ShadowVPN.Desktop*
            !publish/${{ matrix.runtime }}/*.pdb
            !publish/${{ matrix.runtime }}/*.dll
            !publish/${{ matrix.runtime }}/*.json

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Collect required files
        run: |
          mkdir release
          find artifacts -type f -name "ShadowVPN.Desktop.exe" -exec cp {} release/ \;
          find artifacts -type f -name "ShadowVPN.Desktop" ! -name "*.exe" -exec cp {} release/ \;
          ls -la release
      - name: Get previous tag
        id: prevtag
        run: |
          git fetch --tags

          if ! git describe --tags --abbrev=0 >/dev/null 2>&1; then
            echo "tag=v1.0" >> $GITHUB_OUTPUT
            exit 0
          fi

          last_tag=$(git describe --tags --abbrev=0)
          echo "last tag: $last_tag"

          number=$(echo $last_tag | sed 's/v//')
          new=$(awk -v n=$number 'BEGIN { printf "%.1f", n + 0.1 }')
          echo "tag=v$new" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.prevtag.outputs.tag }}
          name: ShadowVPN Release ${{ steps.prevtag.outputs.tag }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
